Added main form to hotels' page
emerell/sedona pull request #2
Opened 2018-11-22 23:51 UTC by emerell

Маю сумніви щодо **input type="range"** . 
В IE ця модна фіча не пітримується((

2018-11-23 06:13 UTC, kryvonos-v commented on hotels.html
> +    <section class="section-y-lg mobile:section-x tablet:section-x filter-box">
А для чого ти розділила секцію на класи `mobile:section-x` i `tablet:section-x`. Для секції можна створити клас `.section-x` який одразу буде поєднувати у собі стилі двох попередніх класів. Тобто на мобільних пристроях по горизонталі `padding` буде 1rem, а для планшетів і далі 4.56rem.

2018-11-23 06:15 UTC, kryvonos-v commented on hotels.html
> +    <section class="section-y-lg mobile:section-x tablet:section-x filter-box">
А взагалі мені подобається ідея того як ти це розбила.

2018-11-23 06:25 UTC, kryvonos-v commented on hotels.html
> +                    <div class="ml-auto tablet-only:mr-auto flex-item">
Зайва обгортка і класи :)
Ті класи, що я написав вище буде достатньо

2018-11-23 06:28 UTC, kryvonos-v commented on hotels.html
> +                <div class="filter__item fgrow-1 aitems-center">
`class="filter__item aitems-center ml-auto mobile:mr-auto"` і тоді ти можеш видалити той `<div>`, що стоїть знизу.

2018-11-23 06:31 UTC, kryvonos-v commented on hotels.html
> +                <div class="filter__item fgrow-1 aitems-center">
Здається, я вам казав, що ви для CSS утиліт використовували такі самі назви як у [Tailwind](https://tailwindcss.com/docs/), тобто:
1) `aitems-center` => `items-center`
2) `fgrow-1` => `flex-gorw`

2018-11-23 06:33 UTC, kryvonos-v commented on hotels.html
> +                <div class="filter__item fgrow-1 aitems-center">
А взагалі ти тут дуже гарно поєднала BEM класи і CSS утиліти 👍

2018-11-23 06:34 UTC, kryvonos-v commented on hotels.html
> +                    <legend class="filter__item-title mb-25">Инфраструктура:</legend>
Про які одиниці вимірювання іде мова`mb-25`? px, em, rem?

2018-11-23 06:44 UTC, kryvonos-v commented on hotels.html
> +                            <span class="filter__vertical-line"></span>
Спробуй зробити цей розділювач через псевдоклас - `.filter__item-price::before` ;)

2018-11-23 06:46 UTC, kryvonos-v commented on hotels.html
> +                            <span class="filter__item-price mb-18">
Я можливо б зреалізував цей елемент як БЕМ блок. Щось типу `from-to-info`. Но это не точно :)

2018-11-23 06:49 UTC, kryvonos-v commented on hotels.html
> +                            <input type="range" name="range" class="range" min="0" max="3500" value="3000" >
Ти сама вже знайшла інформацію про те, що немає **range** з двома повзунками. Тому тобі самій потрібно його зробити :)

2018-11-23 06:52 UTC, kryvonos-v commented on styles/elements/checkbox/output.scss
> +.checkbox label {
БЕМ?)
`.checkbox__label`

2018-11-23 06:54 UTC, kryvonos-v commented on hotels.html
> +            <div class="filter">
Тобі не потрібна ця зайва обгортка. Ти можеш спокійно додати класс `.filter` до тегу `<form>` який стоїть вище

2018-11-23 07:02 UTC, kryvonos-v requested changes
Мені сподобався твій код: дотримувалася БЕМу, сама розібралася як зробити чекбокс, а ще гарно поєднала БЕМ і CSS утиліти.  Молодець!)
Але потрібно зробити декілька правок ;)

2018-11-23 07:06 UTC, kryvonos-v commented on styles/elements/checkbox/output.scss
> +.checkbox input[type=checkbox] {
Тут можна забити на БЕМ))

2018-11-23 07:07 UTC, kryvonos-v commented on styles/elements/checkbox/output.scss
> +.checkbox label:before {
А тут не можна забити на БЕМ

2018-11-23 07:18 UTC, kryvonos-v commented on styles/units/helpers/output.scss
> +  .tablet-only\:mr-auto {
Якщо ми використовуємо частку **only**, то це означає тільки для планшетів, тобто від 769px і до 1024px.
Тому тут більше підійде частка **until** `.until-tablet:mr-auto` або ще можна писати як `.hidden-desktop:mr-auto`. Ось тобі лінк на [Bulma](https://bulma.io/documentation/modifiers/responsive-helpers/), можеш подивитися як вони це назвали і вибрати зручний для себе формат, а краще якщо ми всі разом це узгодимо

2018-11-23 07:23 UTC, kryvonos-v commented on styles/units/helpers/output.scss
> +@media only screen and (max-width: 1024px) {
Якщо ми вже використовуємо bulma для задання breakpoints, то потрібно старатися використовувати їх змінні, тобто замість `1024px` => `$desktop - 1` [(лінк)](https://github.com/jgthms/bulma/blob/master/sass/utilities/initial-variables.sass#L53). А взагалі у bulma для даного випадку як у тебе є спеціальний міксік який називається [`until`](https://github.com/jgthms/bulma/blob/master/sass/utilities/mixins.sass#L77) тобто ти могла написати:
```scss
@include until($desktop) {
 /* your code */
}

2018-11-23 07:30 UTC, kryvonos-v requested changes
Лєра, зроби ще будь ласка, щоб форма пошуку ось так виглядала на мобільних пристроях і планшетах:

![Форма поиска отелей в Седоне для мобильных устройств](https://image.ibb.co/kqGafV/Screen-Shot-2018-11-23-at-8-59-03-AM.png)

2018-11-27 13:52 UTC, emerell commented on hotels.html
> +                    <div class="ml-auto tablet-only:mr-auto flex-item">
Ти хочеш сказати, що всі три класи  _(ml-auto tablet-only:mr-auto flex-item)_ зайві? В тих класах, що були вище, там ж лише padding проставлені

2018-11-27 14:08 UTC, emerell commented on hotels.html
> +                    <div class="ml-auto tablet-only:mr-auto flex-item">
Я цей новий дів додала тоді, коли робила респонсів. В мене блок "Стоимость в сутки" на великих екранах буде притягуватись до правого краю, як на фото, а як тільки стає планшетом, то розташовується по середині свого блоку, тобто вже з'являється невеликий margin з двоз сторін. З одним дівом в мене така штука не виходила(

2018-11-27 14:22 UTC, emerell commented on hotels.html
> +                    <legend class="filter__item-title mb-25">Инфраструктура:</legend>
пікселі, типу якщо без одиниць вимірювання, то пікселі, а якщо rem, то я їх явно прописувала. Можливо й варто додати px.

2018-11-28 14:15 UTC, vladiklem approved these changes
Чет всё оч сложно , честно говоря использование одной трети классов я не понял. Ещё я не знаю на сколько правильно делать миллион модификаторов с одним атрибутом стиля внутри.

2018-11-28 14:15 UTC, vladiklem commented on styles/main.css
> +@keyframes spinAround {
шо это

2018-11-28 14:23 UTC, valeriiamykhalova commented on styles/main.css
> +@keyframes spinAround {
хз, це ж main.css, я його сама не пишу

2018-11-29 12:27 UTC, merged