Created filters for hotels
emerell/sedona pull request #3
Opened 2018-11-29 13:36 UTC by emerell

2018-11-29 14:34 UTC, vladiklem approved these changes

2018-11-29 14:34 UTC, vladiklem commented on hotels.html
> +                    <span class="filter__item-price mb-18">
Не хватает border-radius: 5px .

2018-11-29 14:34 UTC, vladiklem commented on hotels.html
> +                <button type="submit" class="filter__button">Показать</button>
Не хватает border-radius: 5px

2018-11-29 14:34 UTC, vladiklem commented on hotels.html
>      <section>
Это блоковая секция , по этому ей обязательно нужно задать класс , что бы потом вложенные классы называть как отец__сын.

2018-11-29 14:34 UTC, vladiklem commented on hotels.html
> +            <h3 class="mobile:mb-10">
Всем вложенным элементам нужно задавать класс , даже если ты ничего в нём не прописываешь (может понадобиться позже и визуально понятней структура) , кроме тех случаев когда класс очевидно незачем.

2018-11-29 14:34 UTC, vladiklem commented on styles/main.css
> +.sort__item input[type=radio]:checked + .sort__item-label {
input нужно задавать класс и вообще пракически все атрибуты нужно указывать через класс , что бы в случае повторного использования не налаживались уже написанные стили. Но если например для всех span на сайте нужен один набор стилей и ты знаешь это на 100% то можно указать стили и без класса.

2018-11-29 14:34 UTC, vladiklem commented on styles/main.css
> +@media screen and (max-width: 768px) {
Это дело лучше прописывать через @include variable , если есть такая возможность

2018-11-29 14:37 UTC, vladiklem approved these changes

2018-11-29 14:37 UTC, vladiklem commented on hotels.html
> +            <fieldset class="sort">
Если ты поставишь в панели разработчика mobile S то увидишь что последний элемент меню  (По рейтингу) слетает на другую строку. Лично я фиксил эту херню тем что ставил отступы между элементами меню поменьше для мальньких мобил.

2018-12-01 17:54 UTC, taran-d requested changes
І виправ те, що в telegram

2018-12-01 17:54 UTC, taran-d commented on hotels.html
> +        <h2 class="visually-hidden hotels-result-list__title">Найденные гостиницы</h2>
hotels-result-list__title 
DELETE THIS, YOU DONT NEED IT

2018-12-01 17:54 UTC, Rasoft2311 commented on styles/components/result/output.scss
> +  text-align: center;
text-align: center; нічого не робить

2018-12-01 17:54 UTC, Rasoft2311 commented on styles/components/result/output.scss
> +  display:none;
треба не display none, а просто інпуту visually-hidden клас додати

2018-12-01 17:54 UTC, Rasoft2311 commented on styles/components/result/output.scss
> +  display:none;
те саме, visually-hidden

2018-12-03 11:36 UTC, kryvonos-v commented on hotels.html
> +        <section class="section-x section-y-lg result">
Як на мене `result` дуже загальна назва, тому я б змінив на щось типу `search-result`

2018-12-03 11:38 UTC, kryvonos-v commented on hotels.html
> +            <h3 class="mobile:mb-10 result__title">
Я так розумію, ти не хочеш дописувати `px` для утиліт типу `mb-10`?)

2018-12-03 11:40 UTC, kryvonos-v commented on hotels.html
> +                        <svg class="svg" xmlns="http://www.w3.org/2000/svg" width="11" height="10">
При вставці svg картинки на пряму у html документ `xmlns="http://www.w3.org/2000/svg"` атрибут можна видалити

2018-12-03 11:41 UTC, kryvonos-v commented on hotels.html
> +                        <input class="result__pagination-input" type="radio" name="order" value="order-desc" checked form="filter-hotels" id="filter-hotels-order-desc">
Тобі не потрібно додавати префікс `order-` для атрибута `value`, тому що у тебе вже є `name="order"`

2018-12-03 11:45 UTC, kryvonos-v commented on styles/vendors/bulma/sass/utilities/initial-variables.sass
> -$tablet: 769px !default
НІКОЛИ не змінюйте файли вендорів на пряму. При поточній SASS стукрути те що ти зробила буде нормально працювати. Але у майбутньому ми будемо встановалювати Bulma через `npm`. Тобто її файли не будуть частиною проекту

2018-12-03 11:54 UTC, kryvonos-v requested changes
Є маленькі зауваження, а так то все супер :)

2018-12-03 11:54 UTC, kryvonos-v commented on styles/components/result/output.scss
> +.sort__title {
Тут `.sort` - це БЕМ блок, тому всі його стилі повинні знаходитися в окремому файлі:
`components/sort/output.scss`

2018-12-03 11:54 UTC, kryvonos-v commented on hotels.html
> +                    <label for="filter-hotels-order-asc" class="result__pagination-item tablet:mr-10">
Тут краще використати утиліту `mr-10`, а не `tablet:mr-10`, бо тобі потрібно щоб відступ між стрілками був не тільки для планшетів, а й на мобілках. Взагалі, ті відступи у першу чергу повинні бути присутні на телефонах, бо там людина буде тапати по екрану, а не клікати мишкою. Тобто коли ти тапаєш тобі важче попасти по елементах, ніж коли ти це робиш мишкою

2018-12-03 16:27 UTC, merged